= Tour Logger - Systemspezifikation

ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft "Was mache ich"


=== Ausgangssituation
Der WSV Ottensheim ist ein 1971 gegründeter Wassersportverein mit Schwerpunkt auf Rudern, Kanu und Drachenboot.

=== Istzustand
Mitglieder des Vereins speichern ihre Bootsausfahrten in einem Fahrtenbuch.
Derzeit wird das Softwaresystem "efa - elektronisches Fahrtenbuch" eingesetzt.

=== Problemstellung
Für die derzeitige Fahrtenbuch-Softwarelösung gibt es keinen Support mehr.
Änderungen sind daher nicht zu implementieren,
wie zB Änderungen in den Stammdatenstrukturen oder auch Schnittstellen zu anderen Produkten sind nicht möglich,
wie zB zu einem Smartphone-Client

=== Aufgabenstellung
Es wird ein Softwaresystem erstellt,
welches Vereinsmitgliedern erlaubt intuitiv ihre Ausfahrten aufzuzeichnen und zu vergleichen.

==== Funktionale Anforderungen
* Backend
** Quarkus
* Frontends
** Angular
** iOS
** Android

* Funktionalität
** Eintragung von Fahrten
*** eintragen der Wegpunkte auf open street map, wenn gewünscht
*** offline eintragen möglich, falls kein Internet Zugang
*** Änderung und Stornierung von geplanten Fahrten
** Reporting
*** Grafische Darstellung von gefahrenen Kilometern
*** Auflistung von verschiedenen Ranglisten (nach KM allgemein/pro Boot/pro Zeitraum/...)
*** Standardberichte von Fahrten bzw. Gruppen von Fahrten
*** Darstellung von gefahrenen Strecken
*** Bewertung von Fahrern nach ihrer Leistung

==== Use-Case-Diagramm

[plantuml,use-case,png]
----
include::plantuml/use-case-diagram.puml[]
----

==== Nichtfunktionale Anforderungen (NFA)
* Robustheit
** Es sollen Fehler verhindert werden (z.B. keine Doppelten Eintragungen)
* Sicherheit
** Persönliche Daten dürfen nicht von Außenstehenden eingesehen werden
* Effizienz
** Die Fahrer sollen nicht viel Zeit damit verbringen ihre Fahrten einzutragen, sondern sich auf ihre
sportlichen Leistungen konzentrieren können.
* Benutzertauglichkeit
** Der User soll durch ein intuitives Interface schnell und einfach verstehen wie er seine Buchungen durchführen kann.
* Zuverlässigkeit
** Um den Vereinsbetrieb immer flüssig am laufen zu halten, muss unsere Anwendung immer nach Plan funktionieren


=== Ziele
* Einfachere Erfassung von Ausfahrtsdaten
* Motivation der Sportler durch Vergleiche mit anderen.
* Mobile Eingabe/Änderung und darausfolgende Unabhängigkeit vom Boothaus


=== Systementwurf
[plantuml,cld,png]
----
include::plantuml/class-diagram.puml[]
----

=== Systemarchitektur
[plantuml,sysarch,png]
----
include::plantuml/systemarchitektur.puml[]
----