@startuml
@startuml

rectangle Browser {
    rectangle "Angular Client (runtime)" as client
}

rectangle Traefik

client <-down- Traefik
client -down-> Traefik

package "docker-compose - network" {

    rectangle Quarkus

    rectangle Keycloak

    database database

    rectangle nginx {
        rectangle "Angular Client (to be deployed)" as server
    }

}

Traefik <-- Quarkus
Traefik --> Quarkus

Keycloak --> Browser
Browser --> Keycloak
server --> client
Quarkus -left-> database

@enduml