version: '3.3'
services:
#  backend:
#    image: ghcr.io/merisbsc/tour-logger-backend:latest
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql
  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - database:/var/lib/
volumes:
  database:
